### ISSUE TITLE
If a promise is already fulfilled the on_result callback is called without arguments

### ISSUE THREAD

**Issue by NepNep21** [asyncpp/asyncpp#8]
https://github.com/asyncpp/asyncpp/blob/2f887fba4401804b6bb260757f2338be80fa55e5/include/asyncpp/promise.h#L167
This seems like a bug (and prevents my project from compiling) as the same callback is instead called with the appropriate arguments in try_fulfill and try_reject
https://github.com/asyncpp/asyncpp/blob/2f887fba4401804b6bb260757f2338be80fa55e5/include/asyncpp/promise.h#L92
https://github.com/asyncpp/asyncpp/blob/2f887fba4401804b6bb260757f2338be80fa55e5/include/asyncpp/promise.h#L126

**Comment by Thalhammer** [comment]
You are absolutely right, the on_result function was a pretty late addition that was never really tested. I pushed a fix with the proper implementation and test cases for it.

**Comment by NepNep21** [comment]
Thank you.
